import { type NextPage } from "next";
import Head from "next/head";
import MainMenu from "../server/common/Menu";
import Board from "../server/common/Board";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainMenu></MainMenu>
        <div>
            <Board></Board>
        </div>
      </main>
    </>
  );
};

export default Home;
