import { type NextPage } from "next";
import Head from "next/head";
import MainMenu from "../server/common/Menu";
import Board from "../server/common/Board";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Sim ant</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={"h-screen max-h-screen flex flex-col"}>
          <MainMenu></MainMenu>
          <div className={""}>
            <Board></Board>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
